### ISSUE TITLE
Backend server unhealthy

### ISSUE THREAD

**Issue by mokhos** [eumel8/tf-k3s-otc#8]
Hi @eumel8 
I tried out the code. I cannot open rancher via url or IP address(The access via security rules from internet is added). I get unhealthy state on LB (backend-servers). I followed up the issue on otc documentation and turned out the http and https ports are not listening on the servers. 

Could you please help me with that?

**Comment by eumel8** [comment]
@mokhos 
That's very often caused by the significant changes in Traefik loadbalancer. So you should check if there is right installed:

```
% kubectl -n kube-system get services traefik               
NAME      TYPE           CLUSTER-IP    EXTERNAL-IP                   PORT(S)                      AGE
traefik   LoadBalancer   10.43.13.33   10.1.0.160,1.10.0.180   80:31258/TCP,443:30916/TCP   284d
```

then how is the state of the installed rancher

```
% kubectl -n cattle-system get ingress   rancher            
NAME      CLASS    HOSTS                                  ADDRESS                       PORTS     AGE
rancher   <none>   rancher.example.com   10.1.0.160,10.1.0.180   80, 443   284d
```

There is a matrix which Rancher version required specific K3S version. So you not free of choice.

10.1.0.0/24 is the host network like in the default

**Comment by mokhos** [comment]
@eumel8
Thanks for the reply. But there is no ingress and no namespace as "cattle-system" at all. Please look:

![Bildschirmfoto 2022-01-28 um 09 53 43](https://user-images.githubusercontent.com/60837530/151516990-f5f694bc-f912-4f41-97b6-4d2a14dc95c9.png)

![Bildschirmfoto 2022-01-28 um 09 54 38](https://user-images.githubusercontent.com/60837530/151517031-c2f6cd72-f6f1-4624-b04d-0c32b22df001.png)

**Comment by eumel8** [comment]
So, you have a running Kubernetes Cluster,installed cert-manager and that's it. Which Version or Release do you choose? You can check /var/log/cloud-init-output* what's going wrong on Bootstrap.

**Comment by mokhos** [comment]
@eumel8 
Sorry for the late response. I'm trying to use the stable version of K3s. 
And from the cloud-init-output logs I get this:

<img width="838" alt="Bildschirmfoto 2022-02-01 um 09 43 03" src="https://user-images.githubusercontent.com/60837530/151937664-9a3ce141-915b-438c-bc13-b02fd32cea0b.png">

**Comment by eumel8** [comment]
@mokhos What I said: You should bring the configured Rancher version with the K3s version in sync. Here is a support matrix https://www.suse.com/suse-rancher/support-matrix/all-supported-versions/rancher-v2-6-3/

a working example is:

```
rancher_version      = "v2.6.3"
k3s_version          = "v1.22.5+k3s1"
```

**Comment by eumel8** [comment]
it seems the issue is solved for now.
